src/blog/urls.py
from django.urls import path
from .views import post_list, post_create, post_detail, post_update, post_delete


app_name = "blog"
urlpatterns = [
    path("", post_list, name="list"),
    path("create/", post_create, name="create"),
    path("<str:slug>", post_detail, name="detail"),
    path("<str:slug>/update/", post_update, name="update"),
    path("<str:slug>/delete/", post_delete, name="delete"),
]

src/myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User

def user_directory_path(instance, filename):
    return 'blog/{0}/{1}'.format(instance.author.id, filename)

# Create your models here.
# İMAGELARI DATABASEE KAYDETMİYORUZ AWS S3 EN POPÜLER UZAKTA DURMALI dünyanın yarısı orayı kullanıyor

class Category(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name



class Post(models.Model):
    OPTIONS = {
        ("d", "Draft"),
        ("p", "Published")
    }
    title =  models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to=user_directory_path, default="django.jpg")
    category = models.ForeignKey(Category, on_delete = models.PROTECT)
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=OPTIONS, default="d")
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

    def comment_count(self):
        return self.comment_set.all().count()
    
    def view_count(self):
        return self.postview_set.all().count()

    def like_count(self):
        return self.like_set.all().count()

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.user.username


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    POST = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

src/blog/forms.py
from django import forms
from django.db.models import fields
from .models import Post, Comment, Category


class PostForm(forms.ModelForm):
    status = forms.ChoiceField(choices=Post.OPTIONS)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), empty_label="Select")

    class Meta:
        model = Post
        fields = (
            'title',
            'content',
            'image',
            'category',
            'status',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

src/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post
from .forms import PostForm


def post_list(request):
    qs = Post.objects.filter(status="p")
    context = {
        "object_list": qs
    }
    return render(request, "blog/post_list.html", context)


def post_create(request):
    # form = PostForm(request.POST or None, request.FILES or None)
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            # form.save()
            return redirect("blog:list")
    context = {
        'form': form
    }
    return render(request, "blog/post_create.html", context)

def post_detail(request, slug):
    # Post.objects.get(slug=learn-css-086ca595a4)
    obj = get_object_or_404(Post, slug=slug)
    context = {
        "object": obj
    }
    return render(request, "blog/post_detail.html", context)

def post_update(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect("blog:list")

    context = {
        "object": obj,
        "form": form
    }
    return render(request, "blog/post_update.html", context)

def post_delete(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        obj.delete()
        return redirect("blog:list")
    context = {
        "object": obj
    }
    return render(request, "blog/post_delete.html", context)

src/blog/templates/blog/post_create.html
    {% extends "base.html" %}

    {% block content %}

    <form action="" method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">POST</button>
    </form>

    {% endblock content %}

src/blog/templates/blog/post_delete.html
{% extends 'base.html' %}


{% block content %}
<p>Are you sure delete {{ object.title }}</p>
<form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'blog:list' %}">Cancel</a>
    <button type="submit">Yes</button>

</form>

{% endblock content %} 

src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}


{% block content %}

<h1>{{object.title}}</h1>
<img src="{{ object.image.url }}" alt="">
<p>{{object.content}}</p>

{% endblock content %}

src/blog/templates/blog/post_list.html
    {% extends "base.html" %}

    {% block content %}
    <h1 style="text-align: center;">Clarusway Blog</h1>
    <div class="row mt-5">
        {% for obj in object_list %}
        <div class="col-4">
    
            <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem; height: 25rem;">
                <img src="{{ obj.image.url }}" class="card-img-top" alt="post_image">
                <hr>
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'blog:detail' obj.slug %}">{{obj.title}}</a></h5>
                    <p class="card-text">{{obj.content|truncatechars:20}}</p>
                    <p>
                        <span><i class="far fa-comment-alt ml-2"></i>{{ obj.comment_count }} </span>
                        <span><i class="fas fa-eye ml-2"></i>{{ obj.view_count }} </span>
                        <span><i class="far fa-heart ml-2"></i> {{ obj.like_count }}</span>
                    <p class="card-text"><small>
                            Posted {{ obj.publish_date|timesince }} ago.
                        </small>
                    </p>
    
                    </p>
                </div>
            </div>
        </div>
    
        {% endfor %}
    </div>

    {% endblock content %}

src/blog/templates/blog/post_update.html
{% extends "base.html" %} {% block content %}

<h2>Update {{ object.title }}</h2>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
</form>
<button type="submit">Update</button>

{% endblock content %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">

    <title>Hello, world!</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/f347a289b9.js" crossorigin="anonymous"></script>

    -->
</body>

</html> 

src/templates/navbar.html
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:list' %}">Clarusway Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:list' %}">Home</a>
                    <a class="nav-item nav-link" href="#">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="#">Logout</a>
                    <a class="nav-item nav-link" href="#">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'blog:create' %}">New Post</a>
                    {% else %}
                    <a class="nav-item nav-link" href="#">Login</a>
                    <a class="nav-item nav-link" href="#">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>